version: '3.3'
services:
  AzDynDnsv2:
    image: 192.168.1.50:5000/azuredynamicdnsv2:latest
    container_name: AzDynDnsv2
    environment:
      - TZ=Etc/UTC
      - SubscriptionId=00000000-0000-0000-0000-000000000000
      - AZURE_TENANT_ID=00000000-0000-0000-0000-000000000000
      - AZURE_CLIENT_ID=00000000-0000-0000-0000-000000000000
      - AZURE_CLIENT_SECRET=azure_client_secret
      - CreatedBy=AzureDynamicDnsV2
      - ZoneName=mydomain.com
      - ResourceGroup=myresourcegroup
      - RecordNames=mysubdomain
      - TimeToLive=3600
      - UpdateInterval=300
    restart: unless-stopped
